# Generated by Django 5.2 on 2025-06-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='media/yachts/')),
                ('max_passengers', models.PositiveIntegerField(blank=True, null=True)),
                ('cabins', models.PositiveIntegerField(blank=True, null=True)),
                ('guest_beds', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('crew', models.PositiveIntegerField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('power', models.PositiveIntegerField(blank=True, null=True)),
                ('seaworthiness_class', models.CharField(blank=True, max_length=50, null=True)),
                ('hull_type', models.CharField(blank=True, max_length=100, null=True)),
                ('hull_material', models.CharField(blank=True, max_length=100, null=True)),
                ('design_style', models.CharField(blank=True, max_length=100, null=True)),
                ('concept', models.CharField(blank=True, max_length=100, null=True)),
                ('shipyard', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('release_period', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PCPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static', to='common.yacht')),
            ],
        ),
    ]
